-- @metapackage
-- @description MIDI Toolbox - as the name says.
-- @author drvlat
-- @version 0.3.17
-- @provides
--      [nomain] modules/*.lua
--      [main=midi_editor,midi_inlineeditor,midi_eventlisteditor] MIDI_Toolbox_Advanced_Legato.lua
--      [main=midi_editor,midi_inlineeditor,midi_eventlisteditor] MIDI_Toolbox_Quick_Heal_Overlays.lua
--      [main=midi_editor,midi_inlineeditor,midi_eventlisteditor] MIDI_Toolbox_Quick_Legato.lua
--      [main=midi_editor,midi_inlineeditor,midi_eventlisteditor] MIDI_Toolbox_Quick_NonLegato.lua
--      [main=midi_editor,midi_inlineeditor,midi_eventlisteditor] MIDI_Toolbox_CC_Optimizer.lua
--      [main=midi_editor,midi_inlineeditor,midi_eventlisteditor] MIDI_Toolbox_Find_Parallels.lua
--      [main=midi_editor,midi_inlineeditor,midi_eventlisteditor] MIDI_Toolbox_Note_Mover.lua
-- @about
--      This package contains scripts for applying legato effects to MIDI notes.
--      In midi Action List search for:
--          MIDI_Toolbox_Advanced_Legato
--          MIDI_Toolbox_Quick_Heal_Overlays
--          MIDI_Toolbox_Quick_Legato
--          MIDI_Toolbox_Quick_NonLegato
--          MIDI_Toolbox_CC_Optimizer
--          MIDI_Toolbox_Find_Parallels
--          MIDI_Toolbox_Note_Mover
-- @changelog
--      0.3.17 - Fixed "Merge same pitches" button to group all same-pitch notes regardless of distance. Fixed legato merge mode to respect cross-pitch boundaries so different pitches operate independently.
--      0.3.16 - Added "Merge same pitches" button to Advanced Legato (standalone merge for selected notes). Renamed "Merge same-pitch notes" checkbox to "Merge same pitches in legato".
--      0.3.15 - Added "Merge same-pitch notes" option to Advanced Legato (legato slider, Fill gaps, Quick Legato). When enabled, extending a note past same-pitch notes merges them instead of stopping.
--      0.3.14 - Added note mover/copier script for transposing or copying notes by a fixed interval.
--      0.3.12 - Window topmost behavior added to main scripts. Added parallel interval detection script (alpha).
--      0.3.11 - Regression fix
--      0.3.10 - Several bug fixes
--      0.3.9 - Speed optimization, filtering, Bezier conversion.
--      0.3.8 - Project renamed to MIDI Toolbox.
--      0.3.6 - Further optimizations and minor bug fixes.
--      0.3.4 - Integrated CC Tool into Legato package.
--      0.2.4 - Removed MessageBox warnings
--      0.2.3 - Added Quick_NonLegato script
--      0.2.2 - Documentation updates
--      0.2.0 - extracted common functionality to shared library, added quick scripts
--      0.1.6 - resolve all overlays (guaranteed) at once
--      0.1.5 - some minor optimization, proper undo handling
--      0.1.4 - non-deterministic humanization
--      0.1.3 - added Non-legato function and legato humanization.
