-- @metapackage
-- @description Humanize Kontakt Tune Parameter
-- @author drvlat
-- @provides
--      [main] Kontakt_Tune_Humanizer.lua
-- @version 0.0.3
-- @about
--      This package Huamnizes Kontakt #0016 Host parameter (should be assigned to Tune)
-- @changelog
--      0.0.3 - A lot better randomness (Gaussian distribution)
--      0.0.2 - Initial release
